package org.yash.hostelwifi;
import android.app.*;import android.os.*;import android.content.*;import android.net.*;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.webkit.*;import android.widget.*;import org.json.*;import java.net.*;
public final class MainActivity extends Activity {
 LinearLayout page; TextView status; EditText url,user,pass; CheckBox auto; WebView browser; ConnectivityManager cm; int ink=0xff14213a, accent=0xff6750a4, surface=0xfff3edfa; boolean recording=false; final android.content.SharedPreferences.OnSharedPreferenceChangeListener changes=(prefs,key)->{if("status".equals(key)&&status!=null)runOnUiThread(()->status.setText(Config.get(this,"status")));};
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(surface);getWindow().setNavigationBarColor(surface);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);cm=getSystemService(ConnectivityManager.class);if(Build.VERSION.SDK_INT>=31){accent=getColor(android.R.color.system_accent1_600);surface=getColor(android.R.color.system_accent1_10);}showHome();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=getPackageManager().PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},1);}
 GradientDrawable shape(int c,int radius){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(radius);return g;}
 TextView label(String text,int size,boolean bold){TextView t=new TextView(this);t.setText(text);t.setTextColor(ink);t.setTextSize(size);if(bold)t.setTypeface(null,Typeface.BOLD);t.setPadding(0,8,0,8);return t;}
 void setup(String title){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(surface);page=new LinearLayout(this);page.setOrientation(1);page.setPadding(24,36,24,32);scroll.addView(page);setContentView(scroll);page.addView(label(title,32,true));}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(1);c.setPadding(20,18,20,20);c.setBackground(shape(Color.WHITE,36));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=16;page.addView(c,p);return c;}
 Button button(String text,Runnable onClick){Button b=new Button(this);b.setText(text);b.setTextColor(Color.WHITE);b.setTextSize(16);b.setBackground(shape(accent,28));b.setPadding(14,12,14,12);b.setOnClickListener(v->onClick.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=12;page.addView(b,p);return b;}
 EditText field(LinearLayout c,String hint,String value,boolean password){EditText e=new EditText(this);e.setSingleLine(true);e.setTextSize(16);e.setHint(hint);e.setText(value);if(password)e.setInputType(129);e.setPadding(8,16,8,16);c.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
 void service(String action){Intent i=new Intent(this,PortalService.class);if(action!=null)i.putExtra(action,true);try{if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}catch(Exception e){status.setText("Service start blocked: "+e.getMessage());}}
 void showHome(){setup("Hostel Wi-Fi");page.addView(label("Your portal, one tap away",17,false));LinearLayout top=card();top.addView(label("CONNECTION",12,true));status=label(Config.get(this,"status").isEmpty()?"Ready to set up":Config.get(this,"status"),20,true);top.addView(status);page.addView(label("Save the portal address and the credentials you use at college. Record the form once to detect its login fields.",14,false));LinearLayout form=card();url=field(form,"Portal URL, e.g. http://login.college.edu",Config.get(this,"url"),false);user=field(form,"Username",Config.readSecret(this,"user"),false);pass=field(form,"Password",Config.readSecret(this,"pass"),true);button("Save details",()->{Config.put(this,"url",url.getText().toString().trim());Config.secret(this,"user",user.getText().toString());Config.secret(this,"pass",pass.getText().toString());status.setText("Saved securely on this phone");});button("Open portal · record form",()->{saveFields();openPortal();});button("Log in now",()->{saveFields();service("login");new Handler().postDelayed(()->status.setText(Config.get(this,"status")),1800);});button("Ask Android to recheck",()->{service("recheck");status.setText("Requested a network recheck");});auto=new CheckBox(this);auto.setText("Auto login when Android detects a portal");auto.setTextColor(ink);auto.setChecked(Config.p(this).getBoolean("auto",false));auto.setOnCheckedChangeListener((v,checked)->{Config.p(this).edit().putBoolean("auto",checked).apply();service(checked?null:"stop");});page.addView(auto);page.addView(label("Low power: listens to Wi-Fi changes. If your router hides the portal from Android, use Log in now. A captive session may expire later; this app cannot keep the router online while your phone is off.",13,false));if(auto.isChecked())service(null);}
 void saveFields(){Config.put(this,"url",url.getText().toString().trim());Config.secret(this,"user",user.getText().toString());Config.secret(this,"pass",pass.getText().toString());}
 void openPortal(){String s=Config.get(this,"url");if(s.isEmpty())s="http://neverssl.com/";try{URL u=new URL(s);if(!u.getProtocol().equals("http")&&!u.getProtocol().equals("https"))throw new Exception();}catch(Exception e){status.setText("Enter a valid http(s) portal URL");return;}recording=true;setup("Record login form");page.addView(label("Wait for the login page, then tap Save form before signing in. You can sign in normally here to test it.",15,false));browser=new WebView(this);browser.getSettings().setJavaScriptEnabled(true);browser.getSettings().setDomStorageEnabled(true);browser.setWebViewClient(new WebViewClient());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,(int)(getResources().getDisplayMetrics().density*480));page.addView(browser,p);button("Save form on this page",()->captureForm());button("Back to dashboard",()->{closeBrowser();showHome();});Network n=wifi();if(n!=null)cm.bindProcessToNetwork(n);browser.loadUrl(s);}
 Network wifi(){for(Network n:cm.getAllNetworks()){NetworkCapabilities c=cm.getNetworkCapabilities(n);if(c!=null&&c.hasTransport(NetworkCapabilities.TRANSPORT_WIFI))return n;}return null;}
 void captureForm(){if(browser==null)return;String script="(function(){let p=document.querySelector('input[type=password]');if(!p||!p.form)return null;let f=p.form,u=f.querySelector('input[autocomplete=username],input[type=email],input[type=text]');if(!u||!u.name||!p.name)return null;let hidden=[...f.querySelectorAll('input[type=hidden]')].filter(x=>x.name).map(x=>encodeURIComponent(x.name)+'='+encodeURIComponent(x.value)).join('&');return JSON.stringify({action:new URL(f.getAttribute('action')||location.href,location.href).href,method:(f.method||'get').toUpperCase(),username:u.name,password:p.name,extra:hidden});})()";browser.evaluateJavascript(script,v->{try{if(v==null||v.equals("null"))throw new Exception("No standard username/password form found");JSONObject j=new JSONObject(new JSONTokener(v).nextValue().toString());if(!j.getString("method").equals("POST"))throw new Exception("This form uses "+j.getString("method")+"; automatic POST is unsupported");Config.put(this,"action",j.getString("action"));Config.put(this,"usernameField",j.getString("username"));Config.put(this,"passwordField",j.getString("password"));Config.put(this,"extra",j.getString("extra"));Toast.makeText(this,"Form saved. Return and tap Log in now.",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Cannot record: "+e.getMessage(),Toast.LENGTH_LONG).show();}});}
 void closeBrowser(){if(browser!=null){browser.destroy();browser=null;}cm.bindProcessToNetwork(null);recording=false;}public void onBackPressed(){if(recording){closeBrowser();showHome();}else super.onBackPressed();}protected void onResume(){super.onResume();Config.p(this).registerOnSharedPreferenceChangeListener(changes);if(status!=null)status.setText(Config.get(this,"status"));}protected void onPause(){Config.p(this).unregisterOnSharedPreferenceChangeListener(changes);super.onPause();}protected void onDestroy(){if(recording)closeBrowser();super.onDestroy();}
}
