package org.yash.hostelwifi;
import android.app.*;import android.content.*;import android.net.*;import android.os.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.concurrent.*;
public final class PortalService extends Service {
 static final String CH="hostel_status"; ConnectivityManager cm; ConnectivityManager.NetworkCallback cb; final ExecutorService worker=Executors.newSingleThreadExecutor(); volatile boolean busy=false; volatile long last=0; volatile String lastNetwork="";
 public void onCreate(){super.onCreate();if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager.class).createNotificationChannel(new NotificationChannel(CH,"Wi-Fi status",NotificationManager.IMPORTANCE_LOW));Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CH):new Notification.Builder(this);b.setSmallIcon(android.R.drawable.stat_notify_sync).setContentTitle("Hostel Wi-Fi").setContentText("Watching Wi-Fi changes").setContentIntent(PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE));if(Build.VERSION.SDK_INT>=29)startForeground(1,b.build(),android.content.pm.ServiceInfo.FOREGROUND_SERVICE_TYPE_CONNECTED_DEVICE);else startForeground(1,b.build());cm=getSystemService(ConnectivityManager.class);cb=new ConnectivityManager.NetworkCallback(){public void onCapabilitiesChanged(Network n,NetworkCapabilities caps){if(caps.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)){boolean captive=caps.hasCapability(NetworkCapabilities.NET_CAPABILITY_CAPTIVE_PORTAL);boolean validated=caps.hasCapability(NetworkCapabilities.NET_CAPABILITY_VALIDATED);Config.put(PortalService.this,"status",captive?"Portal detected":validated?"Internet verified":"Wi-Fi needs a check");if(captive)attempt(n,false);}}public void onLost(Network n){Config.put(PortalService.this,"status","Wi-Fi disconnected");}};try{cm.registerNetworkCallback(new NetworkRequest.Builder().addTransportType(NetworkCapabilities.TRANSPORT_WIFI).build(),cb);}catch(Exception e){Config.put(this,"status",e.toString());}}
 public int onStartCommand(Intent i,int f,int id){if(i!=null&&i.getBooleanExtra("stop",false)){stopSelf();return START_NOT_STICKY;}if(i!=null&&i.getBooleanExtra("login",false)){Network n=wifi();if(n!=null)attempt(n,true);else Config.put(this,"status","Connect to Wi-Fi first");}if(i!=null&&i.getBooleanExtra("recheck",false)){Network n=wifi();if(n!=null)cm.reportNetworkConnectivity(n,false);}return START_STICKY;}
 Network wifi(){for(Network n:cm.getAllNetworks()){NetworkCapabilities c=cm.getNetworkCapabilities(n);if(c!=null&&c.hasTransport(NetworkCapabilities.TRANSPORT_WIFI))return n;}return null;}
 void attempt(Network n,boolean manual){if(busy)return;long now=System.currentTimeMillis();if(!manual&&lastNetwork.equals(n.toString())&&now-last<120000)return;lastNetwork=n.toString();last=now;busy=true;worker.execute(()->{try{String action=Config.get(this,"action"),user=Config.readSecret(this,"user"),pass=Config.readSecret(this,"pass");if(action.isEmpty()||user.isEmpty()||pass.isEmpty()){Config.put(this,"status","Record the portal form and save credentials");return;}URL u=new URL(action);if(!u.getProtocol().equals("http")&&!u.getProtocol().equals("https"))throw new IOException("Invalid portal URL");String data=URLEncoder.encode(Config.get(this,"usernameField"),"UTF-8")+"="+URLEncoder.encode(user,"UTF-8")+"&"+URLEncoder.encode(Config.get(this,"passwordField"),"UTF-8")+"="+URLEncoder.encode(pass,"UTF-8");String extra=Config.get(this,"extra");if(!extra.isEmpty())data+="&"+extra;HttpURLConnection conn=(HttpURLConnection)n.openConnection(u);conn.setConnectTimeout(8000);conn.setReadTimeout(8000);conn.setInstanceFollowRedirects(false);conn.setRequestMethod("POST");conn.setDoOutput(true);conn.setRequestProperty("Content-Type","application/x-www-form-urlencoded");try(OutputStream out=conn.getOutputStream()){out.write(data.getBytes(StandardCharsets.UTF_8));}int code=conn.getResponseCode();conn.disconnect();Config.put(this,"status","Login sent (HTTP "+code+"); asking Android to verify");cm.reportNetworkConnectivity(n,false);}catch(Exception e){Config.put(this,"status","Login failed: "+e.getMessage());}finally{busy=false;if(!Config.p(this).getBoolean("auto",false))stopSelf();}});}
 public void onDestroy(){if(cb!=null)try{cm.unregisterNetworkCallback(cb);}catch(Exception ignored){}worker.shutdownNow();super.onDestroy();}public android.os.IBinder onBind(Intent i){return null;}
}
